name: "HideCommands"
version: "${version}"
main: "me.kvdpxne.hc.HideCommands"
api-version: "1.7"
load: "STARTUP"
description: "${description}"
authors: ["kvdpxne"]
website: "https://github.com/kvdpxne/hide-commands"
depend: ["ProtocolLib"]
