name: "HideCommands"
version: "${version}"
main: "me.kvdpxne.hc.HideCommands"
load: "STARTUP"
description: "${description}"
authors: ["kvdpxne"]
website: "https://github.com/kvdpxne/hide-commands"
depend: ["ProtocolLib"]
