[versions]
bukkit = "1.8-R0.1-SNAPSHOT"
notchity = "development-SNAPSHOT"
shadow = "8.3.5"
protocollib-legacy = "3.7.0"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
bukkit = { module = "org.bukkit:bukkit", version.ref = "bukkit" }
notchity = { module = "com.github.kvdpxne:notchity", version.ref = "notchity" }
protocollib-legacy = { module = "com.comphenix.protocol:ProtocolLib-Legacy", version.ref = "protocollib-legacy" }